/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
//Serve para guardar o registro traduzido da tabela quando se executa 
import java.sql.ResultSet;

/**
 *
 * @author Administrador
 */
public class TelaControleDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroDepartamento
     */
    public TelaControleDepartamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setTitle("Cadastro de departamentos");
        getContentPane().setLayout(null);

        lblCodigo.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblCodigo.setText("Codigo");
        getContentPane().add(lblCodigo);
        lblCodigo.setBounds(20, 50, 50, 30);

        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(90, 50, 170, 30);

        lblNome.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(20, 100, 50, 30);

        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(90, 100, 400, 30);

        lblCidade.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblCidade.setText("Cidade");
        getContentPane().add(lblCidade);
        lblCidade.setBounds(20, 150, 50, 30);

        txtCidade.setBackground(new java.awt.Color(255, 255, 255));
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtCidade);
        txtCidade.setBounds(90, 150, 330, 30);

        btnPesquisar.setBackground(new java.awt.Color(0, 51, 51));
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(270, 50, 190, 30);

        lblTelefone.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblTelefone.setText("Telefone");
        getContentPane().add(lblTelefone);
        lblTelefone.setBounds(20, 210, 170, 30);

        txtTelefone.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(90, 210, 330, 30);

        btnSalvar.setBackground(new java.awt.Color(0, 51, 51));
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(20, 280, 130, 50);

        btnLimpar.setBackground(new java.awt.Color(0, 51, 51));
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(520, 280, 140, 50);

        btnExcluir.setBackground(new java.awt.Color(0, 51, 51));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(160, 280, 140, 50);

        btnAlterar.setBackground(new java.awt.Color(0, 51, 51));
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(330, 280, 130, 50);

        setSize(new java.awt.Dimension(725, 384));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if (txtCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O código é Obrigatório!");
            txtCodigo.requestFocus();
            return;
        }

        try {
            // - Indicar o nome da classe do driver que está na library do projeto
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/emp_quartas", "root", "212303");
            //Buscar o codigo digitado 
            PreparedStatement st = conectado.prepareStatement("SELECT * FROM departamento WHERE codigo = ?");
            st.setString(1, txtCodigo.getText());
            ResultSet departamento = st.executeQuery(); // Executa o Select na tabela
            if (departamento.next()) {
                txtCidade.setText(departamento.getString("cidade"));
                txtNome.setText(departamento.getString("nome"));
                txtTelefone.setText(departamento.getString("telefone"));
            } else { //Se não encontrou o departamento
                JOptionPane.showMessageDialog(null, "Departamento não encontrado");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O código é Obrigatório!");
            txtCodigo.requestFocus();
            return;
        }
        if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O Nome é Obrigatório!");
            txtNome.requestFocus();
            return;
        }

        try {
            // - Indicar o nome da classe do driver que está na library do projeto
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/emp_quartas", "root", "212303");
            //Inserir os dados digitados na tabela
            PreparedStatement st = conectado.prepareStatement("INSERT INTO departamento VALUES(?, ?, ?, ?)");
            st.setString(1, txtCodigo.getText());
            st.setString(2, txtNome.getText());
            st.setString(3, txtCidade.getText());
            st.setString(4, txtTelefone.getText());
            st.executeUpdate(); // Executa o INSERT na tabela
            //Informar ao usuario que o departamento foi inserido 
            JOptionPane.showMessageDialog(null, "Departamento cadastrado com sucesso");
            // Limpar os campos da tela 
            txtCodigo.setText("");
            txtNome.setText("");
            txtCidade.setText("");
            txtTelefone.setText("");
            txtCodigo.requestFocus();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (SQLException ex) {
            if (ex.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Ops Departamento já cadastrado!");
            } else {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtCodigo.setText("");
        txtNome.setText("");
        txtCidade.setText("");
        txtTelefone.setText("");
        txtCodigo.requestFocus();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (txtCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O código é Obrigatório!");
            txtCodigo.requestFocus();
            return;
        }

        try {
            // - Indicar o nome da classe do driver que está na library do projeto
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/emp_quartas", "root", "212303");
            //Inserir os dados digitados na tabela
            PreparedStatement st = conectado.prepareStatement("DELETE FROM departamento WHERE codigo = ?");
            st.setString(1, txtCodigo.getText());
            st.executeUpdate(); // Executa o DELETE na tabela
            //Informar ao usuario que o departamento foi inserido 
            JOptionPane.showMessageDialog(null, "Departamento excluído com sucesso");
            // Limpar os campos da tela 
            txtCodigo.setText("");
            txtNome.setText("");
            txtCidade.setText("");
            txtTelefone.setText("");
            txtCodigo.requestFocus();

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (txtCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O código é Obrigatório!");
            txtCodigo.requestFocus();
            return;
        }

        try {
            // - Indicar o nome da classe do driver que está na library do projeto
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/emp_quartas", "root", "212303");
            //Inserir os dados digitados na tabela
            PreparedStatement st = conectado.prepareStatement("UPDATE departamento SET nome = ?, cidade = ?, telefone = ? WHERE codigo = ?");
            st.setString(1, txtNome.getText());
            st.setString(2,txtCidade.getText());
            st.setString(3,txtTelefone.getText());
            st.setString(4,txtCodigo.getText());
            st.executeUpdate(); // Executa o UPDATE na tabela
            //Informar ao usuario que o departamento foi inserido 
            JOptionPane.showMessageDialog(null, "Departamento alterado com sucesso");
            // Limpar os campos da tela 
            txtCodigo.setText("");
            txtNome.setText("");
            txtCidade.setText("");
            txtTelefone.setText("");
            txtCodigo.requestFocus();

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaControleDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaControleDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaControleDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaControleDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaControleDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
