/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;

/**
 *
 * @author Administrador
 */
public class TelaCadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroFuncionario
     */
    public TelaCadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCargo = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        lblSalario = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        getContentPane().setLayout(null);

        lblMatricula.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblMatricula.setText("Matricula");
        getContentPane().add(lblMatricula);
        lblMatricula.setBounds(30, 30, 70, 30);

        txtMatricula.setBackground(new java.awt.Color(255, 255, 255));
        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMatricula);
        txtMatricula.setBounds(110, 30, 220, 30);

        lblNome.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(40, 80, 50, 30);

        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(110, 80, 220, 30);

        lblCargo.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblCargo.setText("Cargo");
        getContentPane().add(lblCargo);
        lblCargo.setBounds(40, 130, 50, 30);

        txtCargo.setBackground(new java.awt.Color(255, 255, 255));
        txtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCargo);
        txtCargo.setBounds(110, 130, 220, 30);

        lblSalario.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblSalario.setText("Salário");
        getContentPane().add(lblSalario);
        lblSalario.setBounds(40, 190, 60, 30);

        txtSalario.setBackground(new java.awt.Color(255, 255, 255));
        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtSalario);
        txtSalario.setBounds(110, 190, 220, 30);

        btnSalvar.setBackground(new java.awt.Color(0, 51, 51));
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(40, 250, 170, 40);

        btnPesquisar.setBackground(new java.awt.Color(0, 51, 51));
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(340, 30, 160, 30);

        btnLimpar.setBackground(new java.awt.Color(0, 51, 51));
        btnLimpar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(510, 30, 160, 30);

        btnExcluir.setBackground(new java.awt.Color(0, 51, 51));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(490, 250, 160, 40);

        btnAlterar.setBackground(new java.awt.Color(0, 51, 51));
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(260, 250, 180, 40);

        setSize(new java.awt.Dimension(693, 351));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(txtMatricula.getText().equals("")){
            JOptionPane.showMessageDialog(null, "A Matricula é Obrigatório!");
            txtMatricula.requestFocus();
            return;
        }
        if(txtNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O Nome é Obrigatório!");
            txtNome.requestFocus();
            return;
        }

        try {
            // - Indicar o nome da classe do driver que está na library do projeto
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/emp_quartas","root","212303");
            //Inserir os dados digitados na tabela
            PreparedStatement st = conectado.prepareStatement("INSERT INTO funcionario VALUES(?, ?, ?, ?)");
            st.setString(1,txtMatricula.getText());
            st.setString(2,txtNome.getText());
            st.setString(3,txtCargo.getText());
            st.setString(4,txtSalario.getText());
            st.executeUpdate(); // Executa o INSERT na tabela
            //Informar a Matricula que o funcionario foi inserido
            JOptionPane.showMessageDialog(null, "Funcionario cadastrado com sucesso");
            // Limpar os campos da tela
            txtMatricula.setText("");
            txtNome.setText("");
            txtCargo.setText("");
            txtSalario.setText("");
            txtMatricula.requestFocus();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (SQLException ex) {
            if (ex.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Ops Departamento já cadastrado!");
            } else {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if(txtMatricula.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O Matricula é Obrigatório!");
            txtMatricula.requestFocus();
            return;
        }

        try {
            // - Indicar o nome da classe do driver que está na library do projeto
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/emp_quartas","root","212303");
            //Buscar o codigo digitado
            PreparedStatement st = conectado.prepareStatement("SELECT * FROM funcionario WHERE Matricula = ?");
            st.setString(1,txtMatricula.getText());
            ResultSet departamento  = st.executeQuery(); // Executa o Select na tabela
            if(departamento.next()){
                txtMatricula.setText(departamento.getString("matricula"));
                txtNome.setText(departamento.getString("nome"));
                txtCargo.setText(departamento.getString("cargo"));
                txtSalario.setText(departamento.getString("salario"));
            } else { //Se não encontrou o departamento
                JOptionPane.showMessageDialog(null,"Funcionario não encontrado");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtMatricula.setText("");
        txtNome.setText("");
        txtCargo.setText("");
        txtSalario.setText("");
        txtMatricula.requestFocus();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (txtMatricula.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "A Matricula é Obrigatório!");
            txtMatricula.requestFocus();
            return;
        }

        try {
            // - Indicar o nome da classe do driver que está na library do projeto
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/emp_quartas", "root", "212303");
            //Inserir os dados digitados na tabela
            PreparedStatement st = conectado.prepareStatement("DELETE FROM funcionario WHERE matricula = ?");
            st.setString(1, txtMatricula.getText());
            st.executeUpdate(); // Executa o DELETE na tabela
            //Informar ao usuario que o departamento foi inserido
            JOptionPane.showMessageDialog(null, "Departamento excluído com sucesso");
            // Limpar os campos da tela
            txtMatricula.setText("");
            txtNome.setText("");
            txtCargo.setText("");
            txtSalario.setText("");
            txtMatricula.requestFocus();

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (txtMatricula.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "A Matricula é Obrigatório!");
            txtMatricula.requestFocus();
            return;
        }

        try {
            // - Indicar o nome da classe do driver que está na library do projeto
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/emp_quartas", "root", "212303");
            //Inserir os dados digitados na tabela
            PreparedStatement st = conectado.prepareStatement("UPDATE funcionario SET Matricula = ?, nome = ?, cargo = ?, salario = ? WHERE Matricula = ?");
            st.setString(1, txtMatricula.getText());
            st.setString(2,txtNome.getText());
            st.setString(3,txtCargo.getText());
            st.setString(4,txtSalario.getText());
            st.executeUpdate(); // Executa o UPDATE na tabela
            //Informar ao usuario que o departamento foi inserido
            JOptionPane.showMessageDialog(null, "Matricula alterada com sucesso");
            // Limpar os campos da tela
            txtMatricula.setText("");
            txtNome.setText("");
            txtCargo.setText("");
            txtSalario.setText("");
            txtMatricula.requestFocus();

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
